---
- name: Copy (overwrite) nginx configurations in place.
  template:
    src: "{{ item }}"
    dest: "{{ nginx_main_path }}/{{ item | basename | regex_replace('\\.j2','') }}"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
  with_fileglob: "{{ nginx_configs_source }}/*.j2"
  when: nginx_templates_copy
  notify:
    - validate nginx configuration
    - reload nginx
