- name: Ensure that ssl dir is exist
  file: dest=/etc/ssl mode=0755 owner=root group=root state=directory
  when: nginx_ssl_certs_copy

- name: copy ssl certs
  copy: src={{ nginx_ssl_certs_path }} dest=/etc/ssl/ mode=0400
  notify:
    - validate nginx configuration
    - restart nginx
  when: nginx_ssl_certs_copy

- name: The Diffie-Hellman parameter file is generated
  command: "openssl dhparam -out '/etc/ssl/dhparam2048.pem' 2048"
  args:
    creates: /etc/ssl/dhparam2048.pem
  when: nginx_create_dhparam

- name: Create cron job update the DH params file weekly
  cron:
    name: Ansible - Update DH params file
    job: "openssl dhparam -out '/etc/ssl/dhparam2048.pem' 2048"
    state: present
    special_time: weekly
  when: nginx_dhparam_autoupdate
